### ISSUE TITLE
Subproject support

### ISSUE THREAD

**Issue by neojski** [bbatsov/projectile#1130]
I have a big repo but I mostly work in a particular directory in it. Is possible to treat that subdirectory as a separate projectile project? I'd like to have a special prefix for this subproject so that I could use all the projectile commands inside it but still be able to use the full repo with the default prefix. 

If that's not possible directly would you mind guiding me to the best of in the source code? 

Thank you!

**Comment by prathamesh-sonpatki** [comment]
@neojski Running into same issue as well, have you figured out how to make it work with sub projects?

**Comment by neojski** [comment]
Not really.

My current workflow is opening files that I'll need and then navigate using <kbd>SPC p b</kbd>. I wish I could use <kbd>SPC p h</kbd> but it is unbearably slow when used in big repository.

**Comment by a13** [comment]
you can set projectile-project-root in .dir-locals

**Comment by andreyorst** [comment]
I also have this problem. I have a big repo of notes with notes split to categories, and some of those contain folders that I would like to treat as subprojects. As when I'm working on a particular category of notes I don't want to see other categories. But I don't want to split these notes to different repos.

**Comment by jaden-young** [comment]
I'm not aware of a notion of subprojects, but you can have many projectile projects inside of a source control repo. Either drop a `.projectile` file in the directory root, or use [`M-x projectile-add-known-project`](https://github.com/bbatsov/projectile/blob/905888bbeef850127b74e00292d738469b61cb12/projectile.el#L4161)

**Comment by stardiviner** [comment]
`M-x projectile-add-know-project` does not work. Still `(projectile-project-root)` return parent project path.

**Comment by dmusican** [comment]
I've come across this issue, and I would very much like to see it implemented. Agreed that projectile-add-known-project does not solve the problem.

**Comment by plexus** [comment]
In case anyone else comes here from google, the problem here seems to be that `projectile-root-bottom-up` checks for a different set of files than `projectile-root-top-down`, bottom-up is checked first and only looks for `.projectile` or VCS markers (`.git` etc), only if that doesn't yield anything it will look for project-type specific files like `package.json`, `Gemfile`, etc. So if you have a git repo with subprojects, it will always pick up the `.git`, ignoring the nested projects.

Easy workaround: add the files you care about to `projectile-project-root-files-bottom-up`:

```emacs-lisp
(eval-after-load 'projectile
  (setq projectile-project-root-files-bottom-up
        (cons "package.json"
              projectile-project-root-files-bottom-up)))
```

You might have to reset the project-root-cache

```emacs-lisp
(setq projectile-project-root-cache (make-hash-table :test 'equal))
```
