### ISSUE TITLE
Projectile switch project should show open buffers if any

### ISSUE THREAD

**Issue by pavkum** [bbatsov/projectile#1132]
## Expected behavior
After switching project for huge projects its very tedious to lookout for a buffer. If the buffer is already open if we can display them as open buffers along with existing find file behavior it would be very helpful.

## Actual behavior
Displays list of all the files in the project

## Steps to reproduce the problem
projectile-switch-project-action

### Projectile version information
Projectile version: 20170309.30

### Emacs version
*25.1.2*

### Operating system
ubuntu 16.10

**Comment by evgeniysharapov** [comment]
You can instead open a directory by 
```
(setq` projectile-switch-project-action (lambda () (dired (projectile-project-root))))
```

**Comment by pavkum** [comment]
@evgeniysharapov I would still need to traverse to the file right? In large projects it would still be a pain with lot of directories.

**Comment by evgeniysharapov** [comment]
well, once you are in a project you could use `projectile-find-file` which should eliminate a need to traverse directories, as you can use completion in mini-buffer to find file you want. Perhaps, you can describe your scenario and what needs to happen, because it's not clear for me whether you want to have a file open or directory open upon switching to a project. If you try to open file and you already have a buffer associated with that file, Emacs should switch to that buffer.

**Comment by pavkum** [comment]
@evgeniysharapov Please consider the following example

project p1 has pp1, pp2, pp3 ... 
Project a1 has aa1, aa2, aa3... 
Project x1 has xx1, xx2, xx3...

Now assume I have 2 windows win1 and win2. In win1 I have pp1 opened and in win2 aa1 is opened Now I switch to project x1 in win1 and open file xx1 Now after viewing the file I try to switch back to project p1 in win1. After selecting project from projectile-switch-project projectile list me with all the files of p1 - pp1, pp2, pp3... to select a file and open it. Now since I have already opened pp1 earlier if I could see a list of open buffers along with project files I could save some time.

**Comment by pavkum** [comment]
My workflows have changed. I no longer need to connect to remote machines. Closing the issue.
