### ISSUE TITLE
projectile-discover-projects-in-directory no longer works (for me)

### ISSUE THREAD

**Issue by flamingbear** [bbatsov/projectile#1165]
## Expected behavior

all git repositories are added to my list of projectile projects.

## Actual behavior
No projects are added to my list of projectile projects.
```(projectile-discover-projects-in-directory "/Users/savoie/projects/")(nil nil nil nil nil nil nil nil nil nil nil nil ...)```

## Steps to reproduce the problem
Look at `projectile-bookmarks.eld`
evaluate command `(projectile-discover-projects-in-directory "<path to directory with projects not in bookmarks>")`
look at `projectile-bookmarks.eld`

### Projectile version information

Projectile 20170727.2351

### Emacs version

GNU Emacs 25.2.1 (x86_64-apple-darwin13.4.0, NS appkit-1265.21 Version 10.9.5 (Build 13F1911)) of 2017-04-21

### Operating system

osx sierra
Darwin nsidc-msavoie.users.int.nsidc.org 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64

**Comment by lgmoneda** [comment]
Same problem here.

```
projectile-20170727.2351:

GNU Emacs 25.2.1 (x86_64-apple-darwin13.4.0, NS appkit-1265.21 Version 10.9.5 (Build 13F1911)) of 2017-04-21

System Version: macOS 10.12.5
Kernel Version: Darwin 16.6.0
```

**Comment by jwdunne** [comment]
Wondering if the issue is due to lexical-binding and `default-directory` used as in dynamic binding? E.g output of the following is eq to `pwd`.

`(let ((default-directory "/Users/James/projects/ias-case-review-admin"))
  (projectile-project-root))`

**Comment by jwdunne** [comment]
Appears the problem is due to a 'sticky' `projectile-cached-project-root`. The following quick fix worked for me - not sure if this is the right approach. First time I've ever monkey patched an elisp package function.

```
(defun projectile-discover-projects-in-directory (directory)
  "Discover any projects in DIRECTORY and add them to the projectile cache.
This function is not recursive and only adds projects with roots
at the top level of DIRECTORY."
  (interactive
   (list (read-directory-name "Starting directory: ")))
  (let ((subdirs (directory-files directory t)))
    (mapcar
     (lambda (dir)
       (when (and (file-directory-p dir)
                  (not (member (file-name-nondirectory dir) '(".." "."))))
         (let ((default-directory dir)
               (projectile-cached-project-root dir))
           (when (projectile-project-p)
             (projectile-add-known-project (projectile-project-root))))))
     subdirs)))
```

**Comment by NicholasTD07** [comment]
I am running into this problem too. I can confirm @jwdunne's fix works. Thanks :)

**Comment by zachdaniel** [comment]
@jwdunne Would you (or have you) put up a PR for this? Its definitely a fix and I imagine others could use it too :grinning: 

Thanks for finding it!

**Comment by Chobbes** [comment]
This is busted for me too on  GNU Emacs 25.3.1 (x86_64-pc-linux-gnu) of 2018-02-23

@jwdunne's fix works for me as well, but it would be nice if this worked by default!

**Comment by jwdunne** [comment]
Sorry guys, I missed this. I've made a pull request. I don't really contribute to open source due to time constraints so this is probably my first or second PR - I may have screwed things up!

**Comment by marcofognog** [comment]
I am having a similar symptom, probably for other reasons: 

# Expected behavior
all git repositories are added to my list of projectile projects.

# Actual behavior
No projects are added to my list of projectile projects.
(projectile-discover-projects-in-directory "~/projects/")

## Steps to reproduce the problem
check projectile-bookmarks.eld is empty
check the value of variable projectile-known-projects is empty:

`C-h v projectile-known-projects`

evaluate command (projectile-discover-projects-in-directory "<path to directory with projects not in projectile-known-projects var>")

projectile-bookmarks.eld is still empty ("nil")
projectile-known-projects  var is still empty

## Environment & Version information

No othe lib installed other than projectile.

### Projectile
Package version: 201800808.833
Version: 1.1.0-snapshot

### Emacs version
GNU Emacs 26.1

### Operating system
Linux K42F 4.15.0-30-generic #32-Ubuntu SMP Thu Jul 26 17:42:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

### Work around
Copying and pasting the definition of projectile-discover-projects-in-directory to my .emacs makes it work. Maybe that this gives a clue.
