### ISSUE TITLE
Huge startup perfomance impact

### ISSUE THREAD

**Issue by bomgar** [bbatsov/projectile#1182]
## Expected behavior
Emacs startup is fast

## Actual behavior
Startup emacs (with working_dir=home which is default if started via dmenu) does a lot of IO and takes a long while

## Steps to reproduce the problem
Start emacs. The projectile project type display for the scratchpad takes a really long time.

### Commit
Commit 561d5aa17f7ce01c84b077c3ea2d77e2ae69c095 seems to be causing this. If i checkout the revision before that the problem is gone.

```
(defun projectile-go-project-p ()
  "Check if a project contains Go source files."
  (cl-some
   (lambda (file)
     (string= (file-name-extension file) "go"))
(projectile-current-project-files)))
```
This might be the problem but I'm not sure. `projectile-current-project-files` needs to load all files in my home directory.

Strace shows that the emacs project loads a lot of files on startup. The startup time is probably dependant on the size of the home directory.

### Emacs version

25.3

### Operating system

*Manjaro Linux*

**Comment by bomgar** [comment]
Adding this to my config solves the problem:

```
  (setq projectile-mode-line
        '(:eval (format " Projectile[%s(%s)]"
                        (projectile-project-name))))
```

**Comment by fbertux** [comment]
@bomgar 

Yes, this work to me. Without this code is impossible to work with projectile enable.

**Comment by mriehl** [comment]
Same, thanks for the workaround. Strangely the commandline emacs (`emacs -nw`) starts up quickly, but then slows down to a crawl (feels like it's wading through home in the background) while the ui emacs (`emacs`) seems to do this synchronously and blocks rendering until it's done searching through my home.

**Comment by fbertux** [comment]
I'm using emacs -nw too and startup time is normal, but is very slow to navigate on code with C-p C-n

**Comment by dato** [comment]
Here’s an analysis that you might find useful. (And thank you for providing a workaround in the meantime.)

There are three elements that, combined, I think are enough to explain everybody’s observed behavior. I list them below. First, for this watching along, this is how project detection works:

1. To determine a project type the first time, `projectile-detect-project-type` just cycles through all known project types, until one reports success.

2. Verifying _one_ type is typically very fast: just checking if a file, e.g. _requirements.txt_ exists in the root directory (or sometimes a small number of them, e.g. _Gemfile_ plus _spec_).

3. Once the correct project type is found, the result is cached in a local variable.

And here are the three elements that affect each of the above, making it slow in different scenarios:

1. By cycling through all known types, how many “attempts” are done varies depending on the _order_ of the list of known types. Consider:

   Known types: Python, C++, Go, Java, Ruby.

2. Verifying whether a given project is Go is slow: it potentially visits the whole directory tree. It is _very_ slow, in particular, for non-Go projects!

   Compare, using the list above:

     - Huge C++ project: fast to detect

     - Tiny Ruby project: fast to detect! Since it's tiny, the overhead of checking for Go is negligible.

     - Huge Java project: slow to detect _the first time_, because it recurses the tree in search for a single Go file. Faster afterwards, though: once the correct type was detected, it gets cached.

3. Negative results (i.e. when no type was assigned) are not cached. This explains why “generic” projects are permanently slow: it never hits the cache.

Some possible ameliorations to consider:

  - pushing function-based project detection to the end of the list
  - cache negative results (with care)
  - use "*.go" as a wildcard, and assume there'll always be at least one Go file at top level

Long-term advice to make it faster.

  - do not use `file-expand-wildcards`, since (it seems to me) that will hit the disk for each of the (on average) 15 attempted project types, performing a full readdir() of the project root.

  - instead, modify `projectile-detect-project-type` to perform _only one_ call to obtain the list of top-level file names and then, for each attempted project type:

      - use set intersection if the marker files contain no wildcards
      - use fnmatch if it does
      - pass on that list of top-level file names to types that use a function to detect themselves

I hope this helps.

Thank you for your work on Projectile, I use it everyday and it improved my use of Emacs _a lot_.
