### ISSUE TITLE
projectile-globally-ignored-directories not working with native indexing.

### ISSUE THREAD

**Issue by skrech** [bbatsov/projectile#1250]
## Expected behavior
Ignore non-top-level dirs listed in projectile-globally-ignored-directories with both methods of indexing (native and alien). 

## Actual behavior
Fix introduced in #1119 fixes ignoring of non-top-level dirs for alien indexing mode but not for native.

## Steps to reproduce the problem
1. Put this in init.el:
> projectile-globally-ignored-directories (append '("*\_\_pycache\_\_/")
> 							            projectile-globally-ignored-directories)

2. Run C-u C-c p-f in a python project with generated \_\_pycache\_\_ dirs.
3. The \_\_pycache\_\_ dirs are there even though they have to be ignored.

## Environment & Version information
OSX 10.13 and Windows 10.
Emacs 26.1 and older.
projectile 20180616.252 from Melpa

**Comment by bbatsov** [comment]
Why `*__pychache__`? I don't think we're doing any globbing here.

**Comment by skrech** [comment]
Check #1119 

There is pull request that is merged which enables globs.

**Comment by bbatsov** [comment]
Ah, yeah. I remembered now I wanted to clean this up. 

Well, the problem is pretty simple:

```
(defun projectile-dir-files (directory)
  "List the files in DIRECTORY and in its sub-directories.
Files are returned as relative paths to the project root."
  ;; check for a cache hit first if caching is enabled
  (let ((files-list (and projectile-enable-caching
                         (gethash directory projectile-projects-cache)))
        (root (projectile-project-root)))
    ;; cache disabled or cache miss
    (or files-list
        (if (eq projectile-indexing-method 'native)
            (projectile-dir-files-native root directory)
          ;; use external tools to get the project files
          (projectile-adjust-files (projectile-dir-files-external root directory))))))
```

**Comment by ordnungswidrig** [comment]
@bbatsov trying to get my hands wet, does this mean fixing to filter the result of `projectile-dir-files-native` ?

**Comment by ordnungswidrig** [comment]
In https://github.com/bbatsov/projectile/blob/master/projectile.el#L343 there's a list of globally ignored directories specified, why is `.svn` repeated here and `.csv` is not in the global list. Also why not `.git`. Should this be unified in favour of using `projectile-globally-ignored-directories` only?

**Comment by lanzhiheng** [comment]
@bbatsov The `projectile-globally-ignored-directories` seems not working now.  I am working in the rails project with webpack, but because of the `node_modules` directory it will take me too long time to run `project-find-file`. So I want to exclude the `node_modules`, my configuration like below

![image](https://user-images.githubusercontent.com/8858472/50583778-377fe780-0ea6-11e9-864b-4ef5eafa9e5b.png)

But the problem is I alway get the `node_modules` result when I use `project-find-file`

![image](https://user-images.githubusercontent.com/8858472/50583843-a0fff600-0ea6-11e9-8964-4da018d20d2f.png)

**Comment by nic-donaldson** [comment]
@lanzhiheng are you using the 'alien' indexing method? You would need to add node_modules to your .gitignore in that case.

**Comment by rileyrg** [comment]
unignored still not working today in native. anything in my .gitignore is ignored.

**Comment by rileyrg** [comment]
unignored really should work with hybrid so anything in it overrides the .gitignore.

**Comment by fvides** [comment]
I've hit the same problem: adding node_modules to projectile-globally-ignored-directories doesn't work. After some digging, found that:
* when projectile-indexing-method is 'hybrid delegates the directory file listing to projectile-dir-files-alien and removes files with the fn projectile-remove-ignored
* when there is no vcs, in turn resorts to projectile-generic-command, which has a default value of "find . -type f -print0", which lists all files in current directory prefixed with "./"
* since projectile-remove-ignored uses string-prefix for checking if a file is inside a globally ignored directory, it doesn't recognize ./node_modules/foo as a file contained in globally ignored node_modules directory -> bummer.

So, as a workaround, prefixing node_modules with an asterisk works just fine:
`(add-to-list 'projectile-globally-ignored-directories "*node_modules")`

But I guess the more robust solution would be using proper path analysis for determining that a file should be ignored because an ignored parent. If this is the case, I would gladly work on a patch to fix this, but please confirm @bbatsov.

**Comment by bbatsov** [comment]
@fvides PRs are always welcome! :-)

There's one proposed PR (#1461), but unfortunately it wasn't finished and currently it's not mergeable either.

**Comment by nordlow** [comment]
For me, `projectile-globally-ignored-directories` is respected on Linux but not on Windows.
