### ISSUE TITLE
projectile-recentf broken in latest version

### ISSUE THREAD

**Issue by spindensity** [bbatsov/projectile#1320]
Projectile version: melpa 20181008.812

Emacs version: 26.1

Steps to reproduce:
If `recentf-list` is not `nil`, or, there are some files in recent file list, M-x `projectile-recentf` in any directory NOT belonging to any projects would raise error:
```
Wrong type argument: stringp, nil
```

In latest version, `(projectile-project-root)` returns nil but not current directory when not invoked in project directories. in fuction `projectile-recentf-files`:
```
(let ((project-root (projectile-project-root)))
         (mapcar
          (lambda (f) (file-relative-name f project-root))
          (cl-remove-if-not
           (lambda (f) (string-prefix-p project-root f))
           recentf-list)))
```
`(string-prefix-p nil f)` raised the error.

**Comment by bbatsov** [comment]
> A lot of things does not work in the recent 2 or 3 versions. 

Bug reports would be welcome! :-)

> It seems that are incremental (incomplete) development on the master branch instead of doing it in another branch and merge in when everything is tested.

The only incomplete thing is the situation with `projectile-ensure-project` not being added everywhere, and that's certainly on me - originally I didn't anticipate how much of the code I had to update because of this (and I couldn't just do a global replace). 

> I understand that neither melpa (latest) or master are guaranteed to be stable. However, it is still best practice not to push things to master until a changelist is complete and tested, isn't it?

Well, it's certainly better, but I don't have much time for the project and it also doesn't have good test coverage, so I simply don't have the time to test extensively at this point (there are dozens of commands at this point and so many configuration options that affect their behaviour). All the commands I use on a daily basis were never broken and I simply don't test the rest, so little would have changed if I did most of the feature development off `master`. For me the best approach to fixing this would be to extend the test suite (which is way overdue and I'm currently doing some work there as well). I know that this is less than ideal and not what people want to hear, but that's how OSS projects often work - it's hard to do everything by the book when you simply have almost no time for a project.
See #1303. 

P.S. I'm pretty close to promoting the current build to stable (as it's fairly stable in my opinion), so now's the time to report issues.

**Comment by spindensity** [comment]
Not only `projectile-recentf`, but also almost all commands depend on the return value of `projectile-project-root` are broken or not work as expected when being invoked in a non-project directory.
```
projectile-run-eshell
projectile-find-dir
projectile-find-dir-other-window
projectile-find-dir-other-frame
projectile-dired
projectile-dired-other-window
projectile-dired-other-frame
projectile-multi-occur
projectile-run-shell
projectile-run-eshell
projectile-run-ielm
projectile-run-term
......
```

**Comment by bbatsov** [comment]
@spindensity I've added a few more commits that address the commands you've mentioned.
