### ISSUE TITLE
projectile regenerate tags generate empty tags file

### ISSUE THREAD

**Issue by shelper** [bbatsov/projectile#133]
emacs 24.3 on win 7 with prelude installed, when i use projectile-regenerate-tags function, it failed by saying that invalid 'e' option.

i then noticed that the ctags comes with emacs is not supported, so i installed the exuberant ctags from here http://ctags.sourceforge.net/ by replacing the ctags.exe in the emacs/bin folder. but emacs says that the generated TAGS is not a valid tags table. and if i run projectile-regenerate-tags upon this TAGS file, it becomes empty, with a message saying (Shell command succeeded with no output)

is that because i didn't configure my projectile correctly? or it is a bug for windows version exuberant ctags?

thanks

**Comment by davidshepherd7** [comment]
I had a similar issue on Ubuntu 14.10. It seems that `ctags` now refers to emacs' tag generation program, and the exuberant ctags binary [is now named `ctags-exuberant`](http://askubuntu.com/questions/240284/how-to-run-ctags) (I think this has changed recently). The fix is just to add

    (setq projectile-tags-command "ctags-exuberant -Re %s %s")

to your init file.

**Comment by lidonghai** [comment]
@davidshepherd7 same case, on ubuntu16.04LTS , sudo apt install ctags, then it works well.
