### ISSUE TITLE
Nested project still uses parent gitignore to find files

### ISSUE THREAD

**Issue by didibus** [bbatsov/projectile#1343]
## Expected behavior
Given nested projects inside a git repo.
Given the project root is not the git repo root, but that of a nested project inside it.
Given the git repo .gitignore is set to ignore files.
When I call projectile-find-file. 
Then I expect projectile-find-file to find the files in my project root, irrespective of what is ignored in the .gitignore of the outer git project.

## Actual behavior
Projectile-find-file does not find files that are ignored in the .gitignore.

## Steps to reproduce the problem
- Create a git repo.
- Add a .gitignore which ignores everything `*`
- Create a folder inside, I'll call it `project1`
- Add a `.projectile` file inside the folder
- Now add more files in the folder.
- In emacs, open a file inside of `project1`. You're now supposed to have `project1` as your projectile root.
- Set projectile to use Alien indexing.
- Now, run projectile-find-file, and it will not find anything. Even though your project root is `project1`, it seems it will use the .gitignore and not find anything.

### Projectile version information
```
Projectile 20181028.838
```

### Emacs version
- GNU Emacs 26.1 (build 1, x86_64-suse-linux-gnu, GTK+ Version 3.22.30)

### Operating system
- Linux openSuse

**Comment by bbatsov** [comment]
I think you meant to set hybrid as the indexing method. Alien ignores
.projectile’s contents.

**Comment by didibus** [comment]
I don't have anything inside my `.projectile` file. It is a bit of a special situation, let me explain.

I have my home dir under a git repository. But the only file I have git setup to consider is my `.spacemacs` file. I do this by setting the `.gitignore` file to:

```
# Ignore everything
*

# But not these files...
!.gitignore
!.spacemacs
```

Now, in my home dir, I have a project folder, where I have a bunch of sub-folders in it with each being a project I'm working on in emacs. So inside projectile, I want each of these to be root folders. I do this by having an empty `.projectile` file in each one of them.

So it looks like this:

```
~/.git
~/.gitignore
~/projects/project1/.projectile
~/projects/project2/.projectile
```

The projectile files are empty, since I don't need any files inside the projects folders to be ignored. But, it appears that the projectile indexing set to Alien still uses the `.gitignore` inside my home dir to decide what files to include or exclude. Thus even though I have my projectile root set to `~/projects/project1` and I'm working inside that folder exclusively, projectile is not able to find any files.

I would expect Alien indexing to not look beyond the scope of the project root, and operate as normal. Am I wrong to think that would be possible or desired behavior?

**Comment by anddam** [comment]
I reproduce this with a slightly different and simpler scenario:
a git repo has precedence over a mercurial one, even if the mercurial one is a closer parent and should be _"the project"_.

To reproduce prepare two trees:
```
mkdir -p parent-git/children-hg/src
cd parent-git/; git init
echo children-hg > .gitignore; 
cd children-hg; hg init; 
cd src; echo fubar | tee foo | tee bar

cd ../../../

mkdir -p parent-hg/children-git/src
cd parent-hg/; hg init
echo children-git > .hgignore
cd children-git; git init
cd src; echo fubar | tee foo | tee bar

cd ../../../
```

Now run `emacs parent-git/children-hg/src/foo`, then `counsel-projectile-find-file`.

The expected result should start at `children-hg` and list `src/foo` and `src/bar` since we are editing a file that is direct content of a mercurial repo.

What we see instead is that the search starts at `parent-git` and the only file listed is `.gitignore`.

This means the .gitignore has been honored even if it did not belong to the project.

 

To check the dual case run `emacs parent-hg/children-git/src/foo`, then `counsel-projectile-find-file`.
In this case we see only the files from the inner `children-git` repository listed, and the mercurial ignore file is rightfully ignored, in fact the search show it is correctly starting at `children-git`.

 

There seems to be a preference for git repos and this issue should address that.

**Comment by adab4d** [comment]
@bbatsov any info on this?

I have a git repo in home, a mercurial project in a subfolder and running `projectile-vc` I see
```
VC backend : Git
Working dir: ~/working-area/my-mercurial-repo-hg/
Branch     : master
Remote     : git@gitlab.com.invalid:anddam/dotfiles.git
Stash      : Nothing stashed
```

I see there is a projectile function for find bottom-up, opposed to top-down. Is there a setting to force using that bottom-up search?
