### ISSUE TITLE
[feature request] Project-local variables.

### ISSUE THREAD

**Issue by k-bx** [bbatsov/projectile#139]
Since projectile is already an awesome tool for managing projects in emacs, maybe it could somehow provide users with a documented ability for easily defining (and using in your .emacs file) project-local variables?

**Comment by countvajhula** [comment]
I'm not too familiar with emacs, but what about exposing hooks for this purpose, something like `projectile-project-loaded-hook`? Users can set whatever project-specific variables they care about by using this like any other hook. The issue could be providing additional hooks such that the variables are reset to their original values when a non-project buffer is loaded, but I would assume that mode hooks like `python-mode-hook` already solve this problem. The use case I'm encountering at the moment is that some projects I work on use tabs while others use spaces, and I'd like to set tabstops, tab-indent-mode etc. based on which project it's in.

**Comment by madscientist** [comment]
I've successfully used `.dir-locals.el` for my needs but it is hacky, mainly due to @joelmccracken's issue #1 above: because file local variables are not set until AFTER important things like the mode hooks etc. are parsed, you are very limited in the kinds of things they can affect.

For example, I wanted to customize my LSP server by resetting its initialization options, but that's not possible because LSP starts the server with the global options _before_ `.dir-locals.el` is read in.

You can get this to work, by adding the lsp mode invocation to `hack-local-variables-hook` instead of your mode's hook variable, but it's pretty gross and esoteric.

It would be really nice if there were a more straightforward way to get this to work.  I confess I'm not exactly sure what the right way to do it would be, other than reproducing some aspects of the existing dir-local capabilities.  Or maybe we could ask the Emacs devs to modify the way dir-locals work, so that variables defined in the `nil` context (always applied) are set up before the mode hooks are run and variables defined for a specific mode are set up after the mode hooks are run.  Or something like that...
