### ISSUE TITLE
[QUESTION] How projectile-globally-ignored-files and projectile-globally-ignored-file-suffixes work for native/hybrid/alien

### ISSUE THREAD

**Issue by ywwry66** [bbatsov/projectile#1516]
Since this is only a question, I did not use the template.

I have only used projectile mode for one day and tried to ignore some files globally through `projectile-globally-ignored-files` and `projectile-globally-ignored-file-suffixes`. It turned out the behavior of these two variables are quite different among native/hybrid/alien. Here is what I have found:

Native: `projectile-globally-ignored-file-suffixes` does not work. `projectile-globally-ignored-files` works like regexp.
For example, `(setq projectile-globally-ignored-files '("*.el"))` does not work for me but `(setq projectile-globally-ignored-files '(".*el$"))` works well.

Hybrid: Both `projectile-globally-ignored-file-suffixes`  and `projectile-globally-ignored-files` work. `projectile-globally-ignored-files` needs a exact match.

Alien: Neither variable works.

I have glanced at the code which seems to confirm with observation above. Did I miss something or it is just intended to be like this?

**Comment by bbatsov** [comment]
For alian - it's supposed to work like this for performance reasons - https://docs.projectile.mx/projectile/configuration.html#project-indexing-method

Doing any form of filtering in Emacs is expensive, that's why I feel for most people it's better to rely on `.gitignore` for this type of stuff. STill, if someone needs a second layer of indexing, there's the hybrid indexing for them (external command + post-processing of the result by Emacs). 

I don't quite recall the implementation of `native` and `hybrid` but there might be some room for improvement there.

**Comment by ywwry66** [comment]
Thanks for answering. When I posted this question, I was seeking a portable way for both Windows and macOS. But now I mainly use Emacs on Mac, so I have totally switched to alien indexing mode in conjunction with git, which works fast and robust.

Hopefully, this post can help those new users who run into similar questions in the future. Closing this now.
