### ISSUE TITLE
Many commands fail with stringp type error if called on project-less files

### ISSUE THREAD

**Issue by minad** [bbatsov/projectile#1603]
* projectile-regenerate-tags
* projectile-ibuffer
* ...

I believe this to be a known issue, see for example #1413.

@bbatsov I can go over all interactive commands and check which fail if called without project. Maybe this could also be added to the testsuite and then we can step by step add a check for existing projects. But I am not entirely sure how you would want this to be fixed. Some commands query for a project and some fail. Maybe change the behavior such that all commands simply fail with a clear message and the user has to chose the project first? Would that make sense?

**Comment by bbatsov** [comment]
> Maybe this could also be added to the testsuite and then we can step by step add a check for existing projects.

Yep, that'd be best.

Maybe change the behavior such that all commands simply fail with a clear message and the user has to chose the project first? Would that make sense?

Yep, I agree. That used to be the case originally, before the changes to `projectile-project-root`, that made it return `nil` instead of throwing an error. I guess in most commands that fail all that will be needed is `projectile-ensure-project`.

**Comment by minad** [comment]
For now I found the following failing commands:
~~~
projectile-display-buffer
projectile-find-implementation-or-test-other-frame
projectile-find-implementation-or-test-other-window
projectile-find-other-file
projectile-find-other-file-other-frame
projectile-find-other-file-other-window
projectile-find-test-file
projectile-grep
projectile-ibuffer
projectile-next-project-buffer
projectile-previous-project-buffer
projectile-project-buffers-other-buffer
projectile-project-info
projectile-regenerate-tags
projectile-remove-current-project-from-known-projects
projectile-switch-to-buffer
projectile-switch-to-buffer-other-frame
projectile-switch-to-buffer-other-window
projectile-toggle-between-implementation-and-test
~~~
