### ISSUE TITLE
Broken CI

### ISSUE THREAD

**Issue by bbatsov** [bbatsov/projectile#1604]
Seems an internal change to GH Actions broke the CI. I'm not sure how to fix it though, as supposedly a fix is already present in https://github.com/purcell/setup-emacs

@purcell @doublep Any ideas?

**Comment by purcell** [comment]
That should now be fixed, in v3 of setup-emacs. Not sure why `purcell/setup-emacs@master` isn't now giving you the latest version, because it always used to do the right thing.

**Comment by bbatsov** [comment]
I wonder if there's some way to force GHA to update it. I've started using it recently and my GHA mojo is quite basic.

**Comment by doublep** [comment]
Looks like it is Eldev's installation script that fails, because GitHub apparently disabled `::add-path::` pseudocomand. See [https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/ this article]: apparently deprecation warning days are done with and now this is completely disabled. I updated Eldev's script, but haven't tested it. Can you try to just rerun the Projectile workflows? You can do it from the failed workflow's report page.

**Comment by bbatsov** [comment]
It seems you managed to fix it. Thanks!
