### ISSUE TITLE
SBT, maven: projectile doesn't create the test file if the project already contains one with the required name

### ISSUE THREAD

**Issue by nigredo-tori** [bbatsov/projectile#1650]
## Expected behavior

With `projectile-create-missing-test-files` enabled, when using `projectile-toggle-between-implementation-and-test` in a file like `.../src/main/.../foo.scala`, Projectile should always create a file `.../src/test/.../fooSpec.scala` in the **corresponding** test directory if such file doesn't exist.

## Actual behavior

If the project already contains a file with a name `fooSpec.scala` (in any directory), Projectile opens it instead.

## Steps to reproduce the problem

1. Start with this directory structure ([projectile-example.zip](https://github.com/bbatsov/projectile/files/5994899/projectile-example.zip)):

    ![image](https://user-images.githubusercontent.com/5962285/108189482-5f446f00-7143-11eb-887e-6e8a45c20f13.png)

2. Open `src/main/scala/bar/package.scala`.
3. Execute `projectile-toggle-between-implementation-and-test`.
4. You are now in `src/test/scala/foo/packageSpec.scala` rather than in `src/test/scala/bar/packageSpec.scala`.

The same behavior can be observed in a maven project. I suspect that this happens in any project large enough to have colliding test file names.

### Projectile version information

```
Projectile 20210125.726
```

### Emacs version

GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.20, cairo version 1.16.0)
 of 2021-02-11

### Operating system

Ubuntu 20.10

**Comment by LaurenceWarne** [comment]
Hi @nigredo-tori, are you happy for this to be closed now #1671/#1679 have been merged?

**Comment by nigredo-tori** [comment]
> Hi @nigredo-tori, are you happy for this to be closed now #1671/#1679 have been merged?

 SBT project [hasn't changed](https://github.com/bbatsov/projectile/blob/master/projectile.el#L3134-L31388), so there's a little bit left to be done here. We can try and copy Maven's settings for SBT, the file/directory structures are identical. I have cobbled a more complicated structure for myself a while back:
```scala
  (projectile-update-project-type
   'sbt
   :src-dir
   (lambda (file-path) (projectile-complementary-dir file-path "test" "main"))
   :test-dir
   (lambda (file-path) (projectile-complementary-dir file-path "main" "test")))
  )
```
, although I can't remember why I have chosen this over what we have for Maven in this project.

**Comment by LaurenceWarne** [comment]
> SBT project hasn't changed, so there's a little bit left to be done here. We can try and copy Maven's settings for SBT, the file/directory structures are identical. 

That makes sense.

> , although I can't remember why I have chosen this over what we have for Maven by default.

I agree, iirc the only difference should be if you also had set `:related-files-fn` to something, this would take priority (for test toggling) over the latter (Maven) but not the snippet you gave.

However, atm AFAICS using strings for `:src-dir`/`test-dir` is currently not working as intended since the fallback behaviour https://github.com/bbatsov/projectile/blob/a0858c3079f26b564281f3a51c0ac533bc6e961b/projectile.el#L3574 is currently taking priority over the `projectile--test-file-fallback` function (perhaps confusingly named :smile: ): https://github.com/bbatsov/projectile/blob/a0858c3079f26b564281f3a51c0ac533bc6e961b/projectile.el#L3433 which selects tests based on `:src-dir`/`test-dir` when they are set to strings.

So testing using the project example in your original post and using:
```elisp
(projectile-update-project-type
   'sbt
   :src-dir "main"
   :test-dir "test")
```
Still exhibits the behaviour you described, so I think it makes sense that this issue remains open.  I can PR for this at some point in the close future

**Comment by LaurenceWarne** [comment]
Hi again @nigredo-tori, after #1734 this should hopefully be fixed up now (see https://github.com/bbatsov/projectile/pull/1734#discussion_r768035423 also) - I get the expected behaviour from your initial comment.  Does it look good for you?

**Comment by nigredo-tori** [comment]
@LaurenceWarne, it looks good based on the tests. I'll try and give it a go in the next couple days by removing my workaround, but I expect it to work, so I'm closing this.

Thank you for your work on this!

**Comment by nigredo-tori** [comment]
Just checked, after the update everything works as it should.
