### ISSUE TITLE
Ignoring files does not work

### ISSUE THREAD

**Issue by kek** [bbatsov/projectile#184]
Ignoring files doesn't seem to work. I have created a `.projectile` file in the project with the following contents:

```
-/target
-/project
-/.worksheet
-/.settings
-/TAGS
-/lib_managed
```

Still, when I do `projectile-find-file`, all kinds of crap from `.settings`, `lib_managed` and `target` show up.

I'm using version 0.9.1 on Emacs 24.3.50.1.

**Comment by yatesco** [comment]
I realised this is closed, but are there any plans for helm-projectile-grep to honour .projectile? If not (which is a shame), is there a way I can specify values for vars on a per-projectile-project basis (i.e. ignore XYZ in this project but ABC in that project)?

Thanks!

**Comment by habamax** [comment]
I have the almost the same problem as OP.

My .projectile file is:
```
+/Assets
-*.cs.meta
-*.unity
```
and with `M-x projectile-find-file` I can see that `+/Assets` filter works -- there is a list from that dir. But excluding doesn't work. All files are in the list.

**Comment by habamax** [comment]
Okay, it looks like it basically works... but excluding is not nested.
My previous .projectile should be written as
```
+/Assets
-/Assets/*.cs.meta
-/Assets/*.unity
```

**Comment by featalion** [comment]
I had the same issue with `projectile` + `helm-projectile` + `persp-projectile`. It seems, that projectile's indexing method is changed explicitly by one of the extensions. I've added

```elisp
(setq projectile-indexing-method 'native)
```

into `.emacs.d/init.el` after all `require`s and configurations of the `projectile` and extensions. It fixes the issue for me.

**Comment by nickenchev** [comment]
Switching to the "native" indexer worked, but opening files becomes slower. If I understand correctly, projectile uses Git for it's indexing if it's not using the native method, which is why .projectile ignores are, ignored? No way to combine the two? I have files that need to be in my Git repo, but I really don't like sifting through them when searching for project files, such as dependencies.

Any help would be appreciated, thanks.

**Comment by wpcarro** [comment]
According to the documentation of `projectile-indexing-method`:

```
The alien indexing method optimizes to the limit the speed
of the hybrid indexing method.  This means that Projectile will
not do any processing of the files returned by the external
commands and you're going to get the maximum performance
possible.  This behaviour makes a lot of sense for most people,
as they'd typically be putting ignores in their VCS config and
won't care about any additional ignores/unignores/sorting that
Projectile might also provide.
```

Is this the *desired* behavior or just the current behavior? It seems to me like regardless of indexing method, commands should respect the `.projectile` file.

If that's the case, it shouldn't be too difficult to filter the list of files returned by the `'alien` index by the `.projectile` ignore file.

**Comment by sorawee** [comment]
Also, the documentation at https://projectile.readthedocs.io/en/latest/projects/#ignoring-files claims that 

> The contents of .projectile are ignored when using the alien project indexing method.

But in fact, `hybrid` method also doesn't work.

**Comment by amfern** [comment]
hybrid mode doesn't respect .projectile neither, also i think projectile should respect .ignore file, as it became standard across search tools

**Comment by morgwn** [comment]
> I had the same issue with `projectile` + `helm-projectile` + `persp-projectile`. It seems, that projectile's indexing method is changed implicitly by one of the extensions. I've added
> 
> ```emacs-lisp
> (setq projectile-indexing-method 'native)
> ```
> 
> into `.emacs.d/init.el` after all `require`s and configurations of the `projectile` and extensions. It fixes the issue for me.

This worked for me. Thanks!

**Comment by countvajhula** [comment]
@nickenchev @wpcarro Try using `projectile-ripgrep` together with a `.ignore` or `.rgignore` file. I had this issue as well and finally set some time aside to figure out a solution and wrote it up in [a blog post](https://countvajhula.com/2020/12/07/uncluttered-search-results/) along with some learnings. Hope it helps 👍

**Comment by eayin2** [comment]
> I have following contents in my `.projectile`
> 
> ```
> -/res
> -*.png
> -*.jpg
> ```
> 
> Ignore `-res` works, but `.png` and `.jpg` file still keep show up.
> projectile version: [f5cccda](https://github.com/bbatsov/projectile/commit/f5cccda4d3160b1f82d157baa048b8092ea1ba77)

Omitting the dot worked for me inside `.projectile`. Tried it with native search:
-*toc
-*jpg
-*aux

**Comment by countvajhula** [comment]
Hi @eayin2 ! I notice you downvoted my earlier comment. That's all good, but just curious, did you try my suggestion? If you ran into any issues with it, I'd love to know, since I really think `ripgrep` is the best option here. I'm happy to help if you ran into any issues in getting it working - just post the details of the problem you ran into.

**Comment by eayin2** [comment]
@countvajhula Yes, I tried it and it didn't work for me., but maybe I used it wrongly. I think with ripgrep you search through the contents of the files and not just for the file names? I usually just do `C-c-p-f` and select the file I want to open, not doing something like `grep -R`.

**Comment by countvajhula** [comment]
Ah you're quite right @eayin2 , I didn't realize that some of the discussion here is about the `find-file` feature you're talking about rather than grep search. `ripgrep` ignores would not be recognized by projectile when using the find-file feature -- the only way to get ignores working with find-file seems to be to use native indexing.

Ideally, with alien indexing, projectile should still recognize `projectile-globally-ignored-files` (which @tuhdo mentioned), but it doesn't seem like it does. Until that point, a stopgap option if you're using alien indexing could be to advise the find-file feature to filter the returned list of files:

```
(defun my-projectile-filter-ignores (orig-fn &rest args)
  (let* ((files (apply orig-fn args))
         (ignores (list "/res" "\\.png"))) ; whatever regex you want to exclude
    (seq-filter (lambda (f)
                  (let ((matches (seq-map (lambda (pat)
                                            (string-match-p pat f))
                                          ignores)))
                    (not (seq-reduce (lambda (a b)
                                       (or a b))
                                     matches
                                     nil))))
                files)))
```
Add the advice so that find-file will return the filtered results:
```
(advice-add 'projectile-project-files :around #'my-projectile-filter-ignores)
```
The advice can always be removed:
```
(advice-remove 'projectile-project-files #'my-projectile-filter-ignores)
```

Note that these are _global_ excludes, not per-project. But of course, a proper fix here would be for projectile to recognize `.projectile` excludes (or defer to a standard like `.ignore` as @amfern  suggested) even when using alien indexing.

**Comment by jlabuga** [comment]
I rewrote the solution given by @countvajhula to use patterns and paths defined in `.projectile` files.

The function `my-projectile-filter-ignores` filters the files list with patterns from `projectile-patterns-to-ignore` and paths from `projectile-paths-to-ignore` (theses two variables are defined by projectile from the `.projectile` file):
```emacs
(defun my-projectile-filter-ignores (files)
  "Remove from FILES patterns defined in
`projectile-patterns-to-ignore' and paths defined in
`projectile-paths-to-ignore'.

Setting this function as advice for `projectile-remove-ignored'
permits to use rules defined in .projectile ignoring files, with
the 'hybrid' indexation method."
  (let ((ignored-patterns (projectile-patterns-to-ignore))
         (ignored-paths (projectile-paths-to-ignore)))
    (cl-remove-if
     (lambda (file)
       (or (cl-some
            (lambda (pattern)
              (string-match-p pattern file))
            ignored-patterns)
           (cl-some
            (lambda (dir)
              (string-match-p (concat "\\(\\./\\)+" dir "/") file))
           ignored-paths)))
     files)))
```

The function can be used as advice for  `projectile-remove-ignored`:
```emacs
(advice-add 'projectile-remove-ignored :filter-return #'my-projectile-filter-ignores)
```

With this, I can used `.projectile` files with the `hybrid` indexation method. Without, patterns and paths ignored are not taken into account (with emacs 27.1, doom emacs 6cb2c6e96 and projectile 4d6da87).
