### ISSUE TITLE
speed improvement

### ISSUE THREAD

**Issue by chalmagean** [bbatsov/projectile#3]
Jump to file seems horribly slow, my emacs freezes for 10s on each invocation of jump to file. I do have a ton of files in my rails project, somewhere over 10.000 files.

**Comment by exploid** [comment]
I know that this issue was closed and is fairly old by now but I think it's worth sharing anyways.

I had to add the following to force the cache to be used. Using emacs 24.4.1 on Mac.

```lisp
(setq projectile-enable-caching t)
```

**Comment by Silex** [comment]
there's a cache refactoring going on at #502, it'll take some time but should result in performance improvements.

**Comment by tuhdo** [comment]
@exploid Yes, that's written in the document at the homepage. By default, `projectile` does not enable caching.

Now using external commands, Projectile is really fast, even for generic projects because it uses `find` command, as opposed to pure Emacs Lisp (aka `native` indexing). Probably this was an issue back when `native` indexing is used for unsupported project.

**Comment by exploid** [comment]
This is what I read in the README and I was going off that assumption that it would be on by default since I hadn't customized indexing.

    The caching is enabled by default whenever native indexing is enabled.

**Comment by tuhdo** [comment]
Only when `native` is enabled. By default, on Linux and Mac OS it uses `alien` indexing, so caching is off.
