### ISSUE TITLE
Reorder projectile-project-root-files-functions to detect projects files before vcs.

### ISSUE THREAD

**Issue by proofit404** [bbatsov/projectile#329]
Sometimes project root doesn't match vcs root directory. For example when it stored in subdirectory like src or something. Maybe it's a good idea detect project file markers first, top-down-recurring markers second and bottom-up files last.

**Comment by pronobis** [comment]
The interesting thing is that this is exactly what happens to me without any changes. If i have `.projectile` file in a folder which has multiple repositories in it resulting in sth like: `src/<repo>/.git`, then the main folder has priority and projects do not appear at all for each of the repos.

**Comment by catesandrew** [comment]
This is how a lot of node projects are arranged too but under the `node_modules` directory. I typically add other root markers like `project.json` or `bower.json` to help establish the child directories under `node_modules` as another project. In vi I would open those in another tab, in emacs I could use other tabs but prefer to either switch projects or a new frame since its easier to switch between frames in emacs while its not in vi.

**Comment by proofit404** [comment]
@pronobis And what for 
```
.git/
src/.projectile
```
?
In my opinion `.projectile` file must have greater priority than `.git` directory.

**Comment by billop** [comment]
Are there any workarounds for making "file markers" have precedence over vcs?
