### ISSUE TITLE
Projectile cannot find project root even with .projectile file at root

### ISSUE THREAD

**Issue by tuhdo** [bbatsov/projectile#521]
When I enter a project directory and add a `.projectile` file, Projectile throws the error "You're not in a project" until I restart Emacs to clear `projectile-project-root-cache` and enter the project directory again.

@Silex Could you have a look at this?

**Comment by tuhdo** [comment]
@Silex  Maybe we should use `projectile-project-root-cache` only when the current `default-directory` is remote. Otherwise, let's just disable it for local machine, and this issue is solved.

**Comment by cocreature** [comment]
Just ran into this. Disabling the cache locally sounds like a good way to tackle this. Still for remote directories it should be possible to invalidate the cache even if it's not yet in a project. After all not projects are cached but files and their project roots are cached.

**Comment by Silex** [comment]
@tuhdo: that's not a bad idea... but there was some people mounting "remote" directories as if they were local (nfs, sshfs) and for them the cache is good.

Anyway, I agree the current situation is a mess. What should really be done is a refactor of projectile with structured data (defstruct/eieio) and a global caching mechanism should be used instead of reinventing it at every places (files list, project roots, etc)... for example by using `memoize`. See #502

**Comment by thomasf** [comment]
This was probably the reason why I did only implement a lower level file-exists-p cache previously. I know there was some reason but I do not remember exactly my motivations.

**Comment by bbatsov** [comment]
Any progress here?

**Comment by ReneFroger** [comment]
Still bothered with this bug too. But I'm not sure if it's related to my Windows environment, or with Projectile. Have no idea how I could add a project, even when I'm currently visiting a .projectile-file.

**Comment by tuhdo** [comment]
I made a fix here: https://github.com/bbatsov/projectile/pull/816
