### ISSUE TITLE
project-root-of-file function

### ISSUE THREAD

**Issue by IvanMalison** [bbatsov/projectile#570]
There is currently no way to get the project root of an arbitrary (perhaps unopened) file in projectile. projectile-project-root does approximately the right thing, and could be adapted very easily.

**Comment by emacs18** [comment]
Would something like the following work?

5fa803b1c90085a3c987dfb27b43d32f3b844fe4 HEAD issue_570
Author: Richard Kim <emacs18@gmail.com>
Date:   Sun Mar 1 15:00:53 2015 -0800

    Generalized projectile-project-root to take optional argument for file
    or directory which defaults to current directory.

1 file changed, 10 insertions(+), 5 deletions(-)
 projectile.el | 15 ++++++++++-----

	Modified   projectile.el
diff --git a/projectile.el b/projectile.el
index ff60d26..eee2ec3 100644
--- a/projectile.el
+++ b/projectile.el
@@ -654,11 +654,15 @@ Returns a project root directory path or nil if not found."
    nil
    (or list projectile-project-root-files-top-down-recurring)))
 
-(defun projectile-project-root ()
-  "Retrieves the root directory of a project if available.
-The current directory is assumed to be the project's root otherwise."
+(defun projectile-project-root (&optional path)
+  "Retrieve the project root directory for PATH which defaults to current
+directory.  Return directory of PATH if project root cannot be found."
+  (if path
+      (unless (file-directory-p path)
+        (setq path (file-name-directory path))) ; ensure PATH is a directory
+    (setq path default-directory))
   (file-truename
-   (let ((dir (file-truename default-directory)))
+   (let ((dir (file-truename path)))
      (or (--reduce-from
           (or acc
               (let* ((cache-key (format "%s-%s" it dir))
@@ -672,9 +676,10 @@ The current directory is assumed to be the project's root otherwise."
                     value))))
           nil
           projectile-project-root-files-functions)
+
          (if projectile-require-project-root
              (error "You're not in a project")
-           default-directory)))))
+           path)))))
 
 (defun projectile-file-truename (file-name)
   "Return the truename of FILE-NAME.

[back]

**Comment by emacs18** [comment]
I guess cutting and pasting git diff does not work too well ...

**Comment by IvanMalison** [comment]
@emacs18 Seems like a good idea -- I'd be on board for that.
