### ISSUE TITLE
files not ignored by helm-projectile-find-file

### ISSUE THREAD

**Issue by chalmagean** [bbatsov/projectile#625]
I have my .projectile file set up to ignore *.png, *.jpg, *.gif and while they're successfully ignored by `projectile-find-file` I can see them in the `helm-projectile-find-file` results.

**Comment by tuhdo** [comment]
Are you activating `helm-projectile-find-file` in a Dired buffer? If so, the first source shows all files in your current directory, and the second source shows files the same as `projectile-find-file`, since both uses the same function call to retrieve the file list.

**Comment by chalmagean** [comment]
No, I'm running it while I'm in a project file.

**Comment by tuhdo** [comment]
You're right. However, I see it in `projectile-find-file` as well. Maybe you should try again and type `gif` in `projectile-find-file` to see any gif file? It does appear for me, even the extension is in ignore list.

**Comment by ahwatts** [comment]
I noticed that this was happening with projectile-find-files on Windows (so it's using the 'native indexing scheme). I put an output line in `projectile-ignored-directory-p`, and it looks like `directory` does not have a trailing slash, but the entries in `projectile-ignored-directories` do have a trailing slash. I suspect that commit 5e46193ed2c3 did the breaking.

**Comment by mijoharas** [comment]
I have just installed on windows and even though a folder is present in the `projectile-ignored-directories` it does not get ignored in `helm-projectile-find-files`. This definitely used to work on linux.

**Comment by mijoharas** [comment]
Just updated to the latest version of `projectile` on linux to double check, it only seems to be an issue for windows (for me at least).

**Comment by mijoharas** [comment]
`projectile-current-project-files` seems to give an incorrect result.

**Comment by mijoharas** [comment]
Hmmm... so just been digging into this a bit. gonna document what's going on so that anyone else can (hopefully) jump in and help.

`helm-projectile-find-files` (in `helm-projectile.el` is defined in a macro, which runs helm with a bunch of helm sources. the sources (`helm-source-projectile-files-list`) comprise the actions to be taken (some other things that don't interest us) and the list of files. in this source the list of files (`data`) is `projectile-current-project-files` (in `projectile.el`).

**Comment by mijoharas** [comment]
fixed it. submitting a PR.
