### ISSUE TITLE
Priority of compile/test commands

### ISSUE THREAD

**Issue by chillum** [bbatsov/projectile#693]
In Golang projects, some people use to like Rake or Make wrappers to build and test it (that actually call `go build`/`go test`).

The problem is: when Projectile sees such a project, it assumes the build command to be `go build`. Even if there is a `Rakefille`/`Makefile` in the project.

At current point, the only solution is actually making a config file for Projectile with correct build and test commands. But from my point, that's not the best solution.

That is: if it's a Golang project, we should look for `make` and `rake` files and prefer them to Go commands, if we have one of those. I think, this solution would be the best for Golang programmers.

**Comment by bbatsov** [comment]
In the current `master` branch there's functionality that allows you can register custom project types or configure the compilation/test/run commands on a per-project basis. To me this seems like the best solution, because everyone can adjust Projectile to their preferences instead of Projectile trying to force you to work one way or another.
