### ISSUE TITLE
projectile-regenerate-tags does not ignore files in projectile-globally-ignored-file-suffixes

### ISSUE THREAD

**Issue by jdufresne** [bbatsov/projectile#705]
`projectile-regenerate-tags` appears to only exclude ignored directories. It does not appear to ignore ignored files.

My project has a lot of `.min.js` files that are being added to `TAGS`; creating a very bloated and slow `TAGS` file. I have added `.min.js` to `projectile-globally-ignored-file-suffixes`, but no luck excluding them.

Looking at `projectile-tags-exclude-patterns`, it looks like only directories are excluded.

**Comment by marcinant** [comment]
:+1: 

Yesterday my projectile setup created 286MB TAGS file and reported regexp stack overflow because of that :)

**Comment by jophde** [comment]
I am working on a very large project and despite only including src directories in my .projectile my TAGS file was 13.5GB.

**Comment by justinabrahms** [comment]
Just hit the same error. :-/

**Comment by Deewiant** [comment]
`projectile-tags-exclude-patterns` hasn't changed in the four years since the issue was created, so this seems to still be a valid issue.

2015: https://github.com/bbatsov/projectile/blob/2d190066266fff51812572738fb12850e8b8cc0a/projectile.el#L1748-L1752

2019: https://github.com/bbatsov/projectile/blob/0a4515190291c52278bb0feab7e4d2f6dbf88bc7/projectile.el#L3240-L3244
