### ISSUE TITLE
projectile-ignored-directory-p not ignoring directories on Windows

### ISSUE THREAD

**Issue by ahwatts** [bbatsov/projectile#711]
I've noticed that with recent builds of projectile, it's not ignoring directories like `.git` when indexing a project (on Windows, so when using the native indexing scheme). It appears that the list of directories returned by `projectile-ignored-directories` contains trailing slashes, e.g. `c:/path/to/project/.git/`, while the `directory` argument to `projectile-ignored-directory-p` does not have a trailing slash, e.g. `c:/path/to/project/.git`, making it not match. I can fix this locally by checking for both in `projectile-ignored-directory-p`, but I suspect that it might be symptomatic of some greater misunderstanding in the code.

**Comment by sandor-juhasz** [comment]
I have also run into this issue. Andrew is right, on my Windows machine using native indexing, the `directory-files` function at line 859 returns the directories without trailing slashes and these directory paths are passed to `projectile-ignored-directory-p` at line 855 without transformation. The problem is that `projectile-ignored-directory-p` will match this path to a "canonized" list of ignored directories which all have the trailing slashes so the predicate always returns false. 

I would propose updating the `projectile-ignored-directory-p` to add the trailing slash if necessary before consulting the contents of the map. The `projectile-ignored-directories` function uses `file-name-as-directory` to canonize the directory name so I would use the same in the predicate too. 

```elisp
(defun projectile-ignored-directory-p (directory)
  "Check if DIRECTORY should be ignored."
  (let ((canonical-directory-name (file-name-as-directory directory)))
    (member canonical-directory-name (projectile-ignored-directories))))
```

I can take care of the pull request if we decide to implement this modification.

I have checked the usage of `projectile-ignored-directory-p`, it is used twice, one is the bug above. The other is at line 557, it should be OK as `file-name-directory`always returns the trailing slash.

**Comment by brunoqc** [comment]
@sandor-juhasz thanks for the fix. projectile wasn't usable without it.

**Comment by sandor-juhasz** [comment]
I have just verified if the issue still exists in the current build. A month ago @mijoharas fixed the issue in the following commit: https://github.com/bbatsov/projectile/commit/8849b6066270007b90147f96194a3c45f9b79ccc. The issue can be closed. Thanks Michael for the fix!

**Comment by mijoharas** [comment]
glad to have helped, I noticed the problem but didn't find this thread (or I'd have pointed it out). This issue can be closed.
