### ISSUE TITLE
Use only topmost .git as project

### ISSUE THREAD

**Issue by ghost** [bbatsov/projectile#712]
Hi!

I am working on a codebase that is highly submodulized, which means I always want to jump between submodules and thus would like `projectile` to always simply use the topmost `.git` as project root, and not a submodule. I have tried moving `".git"` between `projectile-project-root-files-bottom-up` and `projectile-project-root-files-top-down` without being able to to achieve this effect.

Is there any way to get what I want?

If not, would you like me to add this to the software or should I just go ahead and submit a PR myself?

Thanks!

**Comment by tuhdo** [comment]
This exists in the past but after some refactoring the feature was lost.

**Comment by jbo-ableton** [comment]
How would you enable the feature in the past? If so, I could try to readd it with the same api as the old one.

**Comment by tuhdo** [comment]
I did not keep track of it for a while, just know that there was a refactoring that removed some code and then it vanished. I may investigate it when I have time.

**Comment by vkz** [comment]
Appears that the requested feature is the default behavior now. Is there any way to treat treat sub-modules as actual separate projects? For instance doing this has absolutely no effect on which ".git" wins (parent-most seems to always win):

```elisp
(setq projectile-project-root-files-bottom-up
        (remove ".git" projectile-project-root-files-bottom-up))
  (add-to-list 'projectile-project-root-files-top-down-recurring ".git")
```

**Comment by jgkamat** [comment]
After a ton of debugging/searching around, I think I finally have a solution for myself, and I'd thought I'd share, since no one has a good solution here. 

First off, the [documentation on the subject sucks](https://github.com/bbatsov/projectile/blob/master/doc/configuration.md#custom-completion-function), and probably needs to be overhauled.

As far as I know, the bottom-up list searches for projects from the current directory up, which is prefect for finding .git folders and other VCS. The bottom-down search searches down from the current directory, making it possible to find projects that are under the current directory. The `projectile-project-root-files-functions` variable controls which one of these strategies run. 

For me, I'm still running into the original issue (where submodules are their own project), and I fixed it by making the `.git` in the bottom-up list to be a folder (`.git/`) instead of a file (`.git`), since submodules have _files_ as their `.git` instead of folders.

If you are having the reverse problem, I would double check your configuration (make sure you are using stock configs) and if you are, then remove or reorder `projectile-root-bottom-up` in `projectile-project-root-files-functions`.

My final adjustments to solve this issue for me:

```
(setq projectile-project-root-files-bottom-up
        (remove ".git" projectile-project-root-files-bottom-up))
(add-to-list 'projectile-project-root-files ".git/")
```

**Comment by bbatsov** [comment]
> First off, the documentation on the subject sucks, and probably needs to be overhauled.

Well, I guess that's a fair point. :-) Improving the documentation is relatively high in my todo list. I've started working in this direction here https://docs.projectile.mx/projectile/projects.html#supported-project-types

I think the simplest way to override the default project resolution is the use of `.projectile` file, but obviously by tweaking `projectile-project-root-functions` you can achieve pretty much everything. 

As the original OP has deleted their account I'll close this ticket.
