### ISSUE TITLE
'(helm-source-buffers-list) '(helm-source-projectile-buffers-list) interaction

### ISSUE THREAD

**Issue by malb** [bbatsov/projectile#750]
I'm trying to combine `helm-source-buffers-list` and `helm-source-projectile-buffers-list` in the same command like this:

``` emacs-lisp
(defun malb/helm-omni (&rest arg)
  ;; just in case someone decides to pass an argument, helm-omni won't fail.
  (interactive)
  (unless helm-source-buffers-list
    (setq helm-source-buffers-list
          (helm-make-source "Buffers" 'helm-source-buffers)))
  (helm-other-buffer
   (append
    (if (projectile-project-p) ;; look before you leap
        '(helm-source-projectile-buffers-list))
   '(helm-source-buffers-list)) "*helm-omni*"))
```

That is, I first want to see the buffers of the current project and then all buffers. However, if I combine these sources they always have the same results (that of the second source), i.e. I see all buffers twice. I'm not sure, though, this is actually a bug or me being daft.

**Comment by xuchunyang** [comment]
As a workaround, you can try to make helm source for projectile buffers by yourself instead of using `helm-source-projectile-buffers-list`, for example:

```elisp
(defun foo ()
  (interactive)
  (helm :sources `(,(helm-make-source "Project buffers" helm-source-buffers
                      :candidates (projectile-project-buffer-names))
                   helm-source-buffers-list)))
```

`helm-source-buffers-list` and `helm-source-projectile-buffers-list` cannot be used at the same time because both of them modify and then use the `helm-buffers-list-cache` variable, I think. 

I guess helm-projectile.el needs some improvements for copying some code from helm-buffers.el.
