### ISSUE TITLE
Can't go to project

### ISSUE THREAD

**Issue by gopar** [bbatsov/projectile#784]
I update projectile and was no longer able to jump to projects when calling `helm-projectile-switch-project`. I would get a `You're not in a project` error. Is this happening to anyone else? 

Last time I update projectile was on June 13, and for helm-projectile June 10. I saw there has been a couple of commits since then. 

I'm on Emacs 24.4.1 in case that matters

NOTE: I can see the list of projects, but when I choose one, I get the error mentioned above.

**Comment by caleb** [comment]
I am getting this as well. I didn't know if it was just me :)

**Comment by bbatsov** [comment]
Likely a recent regression indeed, but I won't be able to investigate this for the next week or so, so it'd be best if someone else took a look in this. Normal project switching works just fine, so this is probably a problem only when using helm. //cc @tuhdo

**Comment by littlemove** [comment]
Same here.

I've went back to revision 695ade3 where this is working (don't know if you could go to a more recent version though).

**Comment by nayefc** [comment]
Same for me. Any fix for this yet?

**Comment by bbatsov** [comment]
I'm pretty busy and I don't use helm myself - someone else should tackle this.

**Comment by nayefc** [comment]
Any ideas how I can downgrade projectile to 0.11.0 then? I've been trying to figure this out for a while and can't get projectile to downgrade. I'll forgo new versions because this is basically making my Emacs set up unusable right now. I'm unfamiliar with the codebase and I'm not sure anyone familiar with the codebase will look into this in a timely manner.

**Comment by nayefc** [comment]
Btw, I removed `(setq projectile-switch-project-action 'projectile-dired)`. How is switch project still using helm-projectile in this case?

**Comment by nayefc** [comment]
Btw, I get an error with `helm-projectile` turned off. `Symbol's value as variable is void`. When Helm is on, I get the You're not in a project error when trying to switch projects. Although I get this symbol error on most other commands. How come this is helm related when I have helm turned off?

**Comment by nayefc** [comment]
Seems like this issue is only on Emacs 24.4. It works fine on Emacs 24.5.

**Comment by bbatsov** [comment]
@tuhdo If you have some time I'd appreciate if you looked into this (and the other issues tagged with `helm`).

**Comment by gopar** [comment]
I upgraded to emacs 24.5. I'm still experiencing the same issue. Not sure what's wrong.

**Comment by gopar** [comment]
Weird. I just updated projectile to see if anything was fixed and BAM! Everything works like a charm. Closing this since I see no issues

**Comment by caleb** [comment]
Just an update for anybody running into this in the future:

I fixed this problem finally. I was using [https://github.com/tarsius/auto-compile](https://github.com/tarsius/auto-compile), and that seems to have been causing the problem since when I remove it from my configuration projectile correctly finds my projects.

Very strange...
