### ISSUE TITLE
find perm change breaks Mac OS X / BSD

### ISSUE THREAD

**Issue by smolyn** [bbatsov/projectile#825]
Recently find -perm +444 was changed to find -perm /444.

This breaks with mac os X find, which uses +.

**Comment by bbatsov** [comment]
See https://github.com/bbatsov/projectile/pull/822 //cc @omajid 

I really regret trying to handle folders with problematic permissions. These ton of issues for something as simple as this reminded me why I didn't want to delegate anything to external tools in the early days of projectile. Guess I'll just kill this functionality and be done with it.

**Comment by omajid** [comment]
Oops. I assumed that the version of `find` on Mac OS X would be newer than 2005...

@bbatsov please feel free to back out my change or kill this entire feature, whichever you see fit. If you like, I can add some version-detection logic to it so that the right `find` command is executed (but maybe that just proves your point about not relying on external tools at all)

Sorry for the breakage :(

**Comment by smolyn** [comment]
It's not that it's old, it's that it's BSD find, not GNU find.

**Comment by lunaryorn** [comment]
I'd really wish that folks were aware that there GNU is not the entire world…

Meanwhile you can `brew install coreutils`, and workaround this issue with `(with-eval-after-load 'projectile (setq projectile-generic-command (concat "g" projectile-generic-command))`.

**Comment by vermiculus** [comment]
@lunaryorn That was the first thing I tried when I found this issue, actually – `gfind` does not exist. (For comparison, `gls` does.)

**Comment by lunaryorn** [comment]
@vermiculus Ah, sorry it's `brew install findutils` for `gfind`.  My bad.

**Comment by bbatsov** [comment]
Just killed this feature altogether. Too much trouble to auto-detect the proper command and it's pretty uncommon to have unreadable folders in a project anyways.

**Comment by lunaryorn** [comment]
@bbatsov Thanks!
