### ISSUE TITLE
how to follow symlink?

### ISSUE THREAD

**Issue by bling** [bbatsov/projectile#83]
i'm trying to get this use case to work:

```
cd ~/dev
git clone repo1
git clone repo2
mkdir both
cd both
ln -s ../repo1
ln -s ../repo2
emacs
```

running projectile-find-file from here gives me a list of nothing (i already have projectile-require-project-root set to nil).  how do i configure it to follow through all symlinks?  is that possible?

thanks!

**Comment by jgarvin** [comment]
The projectile generic command change makes no difference for me. When I combine it with adding an include rule I see the files but the problem then is that I am forced to specify include rules for everything because having one include rule means that only things that are explicitly included are included.
