### ISSUE TITLE
Variable "projectile-globally-ignored-file-suffixes" does not work when finding files

### ISSUE THREAD

**Issue by gamaralf** [bbatsov/projectile#833]
I have set variable "projectile-globally-ignored-file-suffixes" to a list of suffixes that I want to ignore when I use "helm-projectile-find-file" to list files in a project to be opened (visited). Like this:

``` lisp
(setq projectile-globally-ignored-file-suffixes '(".png" ".gif" ".pdf"  "*.class"))
```

However it does not work, files with those suffixes still appear in the helm list.

**Comment by vermiculus** [comment]
For the record, it does work with `projectile-find-file`.

**Comment by ycz0926** [comment]
i also meet the same problem, how to solve it?

**Comment by shreve** [comment]
Same here

```elisp
(setq projectile-globally-ignored-file-suffixes '(".png" ".jpg" ".gif" ".woff" ".woff2" ".ttf" ".cache"))
```

Running `projectile-find-file` still returns results with `.png` and `.woff` extensions

**Comment by losingkeys** [comment]
Same issue here with the value `'("~")`. Running `projectile-invalidate-cache` and/or restarting Emacs appears to have no effect. Happy to help test patches, but both cursory searching through the codebase hasn't turned anything up and using customize to ensure I'm creating the variable correctly hasn't done it.

**Comment by nordlow** [comment]
I also have this problem. Anybody have a solution to this issue or hints on which function that should be modified to fix ti?

**Comment by morgwn** [comment]
Also active bug here.

**Comment by andrewsw** [comment]
Following up. A restart of emacs seems to have resolved this issue for me. However, I have two customizations in place -- `projectile-globally-ignored-directories` and `projectile-globally-ignore-file-suffixes`. I'm unsure which is actually having impact.

**Comment by fm4d** [comment]
Are you sure that your are not using alien indexing method that does not do any postprocessing?

**Comment by alecvn** [comment]
This is still an issue.

**Comment by viseztrance** [comment]
Agreed, the issue is still present. Could this be reopened?

**Comment by sittingbull** [comment]
Hello
Apparently the [docs](https://docs.projectile.mx/projectile/configuration.html) state that using alien indexing (which is the default indexing behaviour for max/linux) will by design avoid all post-processing by projectile, which implies that projectile-globally-... variable contents will not be taken into account. .

The two available options, as I understand it from reading the manual, are to 1/ explicitly switch to either hybrid or native indexing method, or 2/ customize the projectile-generic-command for projects with no VCS (since for projects with VCS you can use the VCS ignore system anyway)
Best

**Comment by rileyrg** [comment]
Im using native and it still uses files in the suffix exclude to search. Also something like "-*.md'  in .projectile is not honoured and helm-projectile-grep still searches .md files.
